# permissions for end users to edit checlusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checluster-editor-role
rules:
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusters/status
  verbs:
  - get
