apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: che-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: The `CheCluster` custom resource allows defining and managing a Che server installation
      displayName: Che Cluster
      kind: CheCluster
      name: checlusters.org.eclipse.che
      version: v1
  description: Install Eclipse Che
  displayName: che-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ide
  - cloud development
  - Kubernetes
  - Openshift
  links:
  - name: Che Operator
    url: https://che-operator.domain
  maturity: alpha
  provider:
    name: Eclipse
    url: https://github.com/eclipse-che/che-operator
  version: 0.0.0
