#
#  Copyright (c) 2012-2019 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-operator
rules:
  - apiGroups:
      - oauth.openshift.io
    resources:
      - oauthclients
    verbs:
      - create
      - get
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
    verbs:
      - get
  - apiGroups:
      - user.openshift.io
    resources:
      - users
    verbs:
      - list
  - apiGroups:
      - console.openshift.io
    resources:
      - consolelinks
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - list
      - watch
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - create
      - list
      - watch
  - apiGroups:
      - authorization.openshift.io
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - get
      - create
  - apiGroups:
      - authorization.openshift.io
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - update
      - create
  - apiGroups:
    - org.eclipse.che
    resources:
    - checlusters/finalizers
    verbs:
    - '*'
# Create namespaces rules. Needed to delegate them to Che server.
  - verbs:
      - create
      - update
    apiGroups:
      - project.openshift.io
    resources:
      - projectrequests
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - update
# Manage namespace rules.Needed to delegate them to Che server.
  - verbs:
      - get
      - create
    apiGroups:
      - authorization.openshift.io
      - rbac.authorization.k8s.io
    resources:
      - roles
  - verbs:
      - get
      # check it
      - update
      - create
    apiGroups:
      - authorization.openshift.io
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
  - verbs:
      - get
    apiGroups:
      - project.openshift.io
    resources:
      - projects
  - verbs:
      - get
      - create
      - watch
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
      - configmaps
  - verbs:
      - list
    apiGroups:
      - apps
    resources:
      - secrets
  - verbs:
      - list
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - create
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
  - verbs:
      - get
      - list
      - create
      - watch
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - create
      - patch
      - watch
      - delete
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - list
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - list
      - create
      - delete
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - watch
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - list
      - get
      - patch
      - delete
    apiGroups:
      - apps
    resources:
      - replicasets
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - list
      - create
      - watch
      - get
      - delete
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
