apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: che-operator
  name: controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: che-operator
status:
  loadBalancer: {}
