#
# Copyright (c) 2012-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation

name: Migrate manifest format packages to the OLM bundles

on:
  schedule:
    - cron:  '10 10 * * *'
jobs:

  build:
    name: Bundle migration
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Docker login
      run: echo "===A===" && date +"%H:%M"

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Migrate manifest format packages to the OLM bundles
      run: "${GITHUB_WORKSPACE}/olm/buildOLMBundlesFromReleaseManifestFiles.sh"
      env:
        IMAGE_REGISTRY_HOST: quay.io
        IMAGE_REGISTRY_USER_NAME: aandriienko