#
#  Copyright (c) 2012-2021 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
#
name: Push catalog and bundle images.
on:
  schedule:
    - cron:  '55 16 * * *'
  pull_request:
      branches:
        - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Install yq
      run: sudo pip install yq

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build catalog source and opm bundle images and push
      run: "${GITHUB_WORKSPACE}/olm/push-catalog-and-bundle-images.sh -c nightly -p 'kubernetes' -p 'openshift'"
      env:
        # Todo: set up eclipse org
        IMAGE_REGISTRY_HOST: aandrienko
        IMAGE_REGISTRY_USER_NAME: quay.io
