# This Workflow creates PRs for the release of the latest che-operator to the community operators in OperatorHub
name: Release community operator PRs
on:
  # manual trigger if required
  workflow_dispatch:
    inputs:
      forceflag:
        description: 'To update an existing PR, use -f or --force flag here'
        default: ''
  # trigger on commit to master branch of new CSVs, eg., https://github.com/eclipse/che-operator/pull/571/files
  push:
    branches: 
      - master
    paths:
      - 'deploy/olm-catalog/stable/eclipse-che-preview-*/manifests/che-operator.clusterserviceversion.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install operator courier, yq
        run: |
          python -m pip install --upgrade pip
          pip install operator-courier==2.1.7
          pip install yq
      - name: Release community operator PRs
        run: |
          echo "Test"