# This Workflow creates PRs for the release of the latest che-docs
name: Release che docs
on:
  # manual trigger if required
  workflow_dispatch:
    inputs:
      version:
        description: 'The version that is going to be released. Should be in format 7.y.z'
        required: true
        default: '7.y.z'
      forceflag:
        description: 'To force creation of .x branch, use --force flag here'
        default: ''
  # trigger on commit to master branch of new CSVs, eg., https://github.com/eclipse/che-operator/pull/571/files
  push:
    branches: 
      - master
    paths:
      - 'deploy/olm-catalog/stable/eclipse-che-preview-*/manifests/che-operator.clusterserviceversion.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release che docs PRs
        run: |
          echo "Test"